//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UDIRS.nsWebServices {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ud.edu.sa/api/ldap", ConfigurationName="nsWebServices.ldapSoap")]
    public interface ldapSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ud.edu.sa/api/ldap/UserValid", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool UserValid(string UserName, string PassWord, string usr_user, string usr_pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ud.edu.sa/api/ldap/GetUser", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetUser(string UserName, string PassWord, string usr_user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ud.edu.sa/api/ldap/GetUser_", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        UDIRS.nsWebServices.GetUser[] GetUser_(string UserName, string PassWord, string usr_user, bool lang);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ud.edu.sa/api/ldap/GetUserByNationalID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        UDIRS.nsWebServices.GetUser[] GetUserByNationalID(string UserName, string PassWord, string usr_id, bool lang);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ud.edu.sa/api/ldap/UserIsExists", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool UserIsExists(string UserName, string PassWord, string usr_user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ud.edu.sa/api/ldap/ForgetPassword", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool ForgetPassword(string UserName, string PassWord, string usr_user, string verify, string new_pass, bool is_valid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ud.edu.sa/api/ldap/ChangePassword", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool ChangePassword(string UserName, string PassWord, string usr_user, string old_pass, string new_pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ud.edu.sa/api/ldap/Search", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        UDIRS.nsWebServices.GetAccount[] Search(string UserName, string PassWord, int category, string text, bool lang);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ud.edu.sa/api/ldap/CreateUser", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string CreateUser(string UserName, string PassWord, string uPath, string userUname, string userPassword, string fName, string mName, string lName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ud.edu.sa/api/ldap/AssignUserToGroup", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool AssignUserToGroup(string UserName, string PassWord, string usr_user, string groupPath);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ud.edu.sa/api/ldap/DropUserFromGroup", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool DropUserFromGroup(string UserName, string PassWord, string usr_user, string groupPath);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ud.edu.sa/api/ldap/DeleteUser", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool DeleteUser(string UserName, string PassWord, string userUname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ud.edu.sa/api/ldap/UnlockUser", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void UnlockUser(string UserName, string PassWord, string usr_user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ud.edu.sa/api/ldap/RemoveUserFromGroup", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool RemoveUserFromGroup(string UserName, string PassWord, string usr_user, string groupPath);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ud.edu.sa/api/ldap")]
    public partial class GetUser : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string fullNameField;
        
        private string emailField;
        
        private string isLockedField;
        
        private string phoneField;
        
        private string mobileField;
        
        private string idField;
        
        private string noField;
        
        private string nationalityField;
        
        private string birthDateField;
        
        private string birthPlaceField;
        
        private string socialStatusField;
        
        private string companyField;
        
        private string buildingField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string FullName {
            get {
                return this.fullNameField;
            }
            set {
                this.fullNameField = value;
                this.RaisePropertyChanged("FullName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("Email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string IsLocked {
            get {
                return this.isLockedField;
            }
            set {
                this.isLockedField = value;
                this.RaisePropertyChanged("IsLocked");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
                this.RaisePropertyChanged("Phone");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Mobile {
            get {
                return this.mobileField;
            }
            set {
                this.mobileField = value;
                this.RaisePropertyChanged("Mobile");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string No {
            get {
                return this.noField;
            }
            set {
                this.noField = value;
                this.RaisePropertyChanged("No");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Nationality {
            get {
                return this.nationalityField;
            }
            set {
                this.nationalityField = value;
                this.RaisePropertyChanged("Nationality");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string BirthDate {
            get {
                return this.birthDateField;
            }
            set {
                this.birthDateField = value;
                this.RaisePropertyChanged("BirthDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string BirthPlace {
            get {
                return this.birthPlaceField;
            }
            set {
                this.birthPlaceField = value;
                this.RaisePropertyChanged("BirthPlace");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string SocialStatus {
            get {
                return this.socialStatusField;
            }
            set {
                this.socialStatusField = value;
                this.RaisePropertyChanged("SocialStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string Company {
            get {
                return this.companyField;
            }
            set {
                this.companyField = value;
                this.RaisePropertyChanged("Company");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string Building {
            get {
                return this.buildingField;
            }
            set {
                this.buildingField = value;
                this.RaisePropertyChanged("Building");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ud.edu.sa/api/ldap")]
    public partial class GetAccount : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string displayNameField;
        
        private string employeeNumberField;
        
        private string employeeIDField;
        
        private string mobileField;
        
        private string companyField;
        
        private string departmentField;
        
        private string physicalDeliveryOfficeNameField;
        
        private string secondryEmailField;
        
        private string hiringDateField;
        
        private string birthDateField;
        
        private string telephoneNumberField;
        
        private string facsimileTelephoneNumberField;
        
        private string employeeTypeField;
        
        private string givenNameField;
        
        private string middleNameField;
        
        private string snField;
        
        private string ipPhoneField;
        
        private string emailField;
        
        private string sAMAccountNameField;
        
        private string prefixField;
        
        private string jobLocationField;
        
        private string titleField;
        
        private string otherMobileField;
        
        private string infoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string displayName {
            get {
                return this.displayNameField;
            }
            set {
                this.displayNameField = value;
                this.RaisePropertyChanged("displayName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string employeeNumber {
            get {
                return this.employeeNumberField;
            }
            set {
                this.employeeNumberField = value;
                this.RaisePropertyChanged("employeeNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string employeeID {
            get {
                return this.employeeIDField;
            }
            set {
                this.employeeIDField = value;
                this.RaisePropertyChanged("employeeID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string mobile {
            get {
                return this.mobileField;
            }
            set {
                this.mobileField = value;
                this.RaisePropertyChanged("mobile");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string company {
            get {
                return this.companyField;
            }
            set {
                this.companyField = value;
                this.RaisePropertyChanged("company");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string department {
            get {
                return this.departmentField;
            }
            set {
                this.departmentField = value;
                this.RaisePropertyChanged("department");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string physicalDeliveryOfficeName {
            get {
                return this.physicalDeliveryOfficeNameField;
            }
            set {
                this.physicalDeliveryOfficeNameField = value;
                this.RaisePropertyChanged("physicalDeliveryOfficeName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string secondryEmail {
            get {
                return this.secondryEmailField;
            }
            set {
                this.secondryEmailField = value;
                this.RaisePropertyChanged("secondryEmail");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string hiringDate {
            get {
                return this.hiringDateField;
            }
            set {
                this.hiringDateField = value;
                this.RaisePropertyChanged("hiringDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string birthDate {
            get {
                return this.birthDateField;
            }
            set {
                this.birthDateField = value;
                this.RaisePropertyChanged("birthDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string telephoneNumber {
            get {
                return this.telephoneNumberField;
            }
            set {
                this.telephoneNumberField = value;
                this.RaisePropertyChanged("telephoneNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string facsimileTelephoneNumber {
            get {
                return this.facsimileTelephoneNumberField;
            }
            set {
                this.facsimileTelephoneNumberField = value;
                this.RaisePropertyChanged("facsimileTelephoneNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string employeeType {
            get {
                return this.employeeTypeField;
            }
            set {
                this.employeeTypeField = value;
                this.RaisePropertyChanged("employeeType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string givenName {
            get {
                return this.givenNameField;
            }
            set {
                this.givenNameField = value;
                this.RaisePropertyChanged("givenName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string middleName {
            get {
                return this.middleNameField;
            }
            set {
                this.middleNameField = value;
                this.RaisePropertyChanged("middleName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string sn {
            get {
                return this.snField;
            }
            set {
                this.snField = value;
                this.RaisePropertyChanged("sn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string ipPhone {
            get {
                return this.ipPhoneField;
            }
            set {
                this.ipPhoneField = value;
                this.RaisePropertyChanged("ipPhone");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string SAMAccountName {
            get {
                return this.sAMAccountNameField;
            }
            set {
                this.sAMAccountNameField = value;
                this.RaisePropertyChanged("SAMAccountName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string prefix {
            get {
                return this.prefixField;
            }
            set {
                this.prefixField = value;
                this.RaisePropertyChanged("prefix");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string jobLocation {
            get {
                return this.jobLocationField;
            }
            set {
                this.jobLocationField = value;
                this.RaisePropertyChanged("jobLocation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
                this.RaisePropertyChanged("title");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string otherMobile {
            get {
                return this.otherMobileField;
            }
            set {
                this.otherMobileField = value;
                this.RaisePropertyChanged("otherMobile");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string info {
            get {
                return this.infoField;
            }
            set {
                this.infoField = value;
                this.RaisePropertyChanged("info");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ldapSoapChannel : UDIRS.nsWebServices.ldapSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ldapSoapClient : System.ServiceModel.ClientBase<UDIRS.nsWebServices.ldapSoap>, UDIRS.nsWebServices.ldapSoap {
        
        public ldapSoapClient() {
        }
        
        public ldapSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ldapSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ldapSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ldapSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool UserValid(string UserName, string PassWord, string usr_user, string usr_pass) {
            return base.Channel.UserValid(UserName, PassWord, usr_user, usr_pass);
        }
        
        public System.Data.DataSet GetUser(string UserName, string PassWord, string usr_user) {
            return base.Channel.GetUser(UserName, PassWord, usr_user);
        }
        
        public UDIRS.nsWebServices.GetUser[] GetUser_(string UserName, string PassWord, string usr_user, bool lang) {
            return base.Channel.GetUser_(UserName, PassWord, usr_user, lang);
        }
        
        public UDIRS.nsWebServices.GetUser[] GetUserByNationalID(string UserName, string PassWord, string usr_id, bool lang) {
            return base.Channel.GetUserByNationalID(UserName, PassWord, usr_id, lang);
        }
        
        public bool UserIsExists(string UserName, string PassWord, string usr_user) {
            return base.Channel.UserIsExists(UserName, PassWord, usr_user);
        }
        
        public bool ForgetPassword(string UserName, string PassWord, string usr_user, string verify, string new_pass, bool is_valid) {
            return base.Channel.ForgetPassword(UserName, PassWord, usr_user, verify, new_pass, is_valid);
        }
        
        public bool ChangePassword(string UserName, string PassWord, string usr_user, string old_pass, string new_pass) {
            return base.Channel.ChangePassword(UserName, PassWord, usr_user, old_pass, new_pass);
        }
        
        public UDIRS.nsWebServices.GetAccount[] Search(string UserName, string PassWord, int category, string text, bool lang) {
            return base.Channel.Search(UserName, PassWord, category, text, lang);
        }
        
        public string CreateUser(string UserName, string PassWord, string uPath, string userUname, string userPassword, string fName, string mName, string lName) {
            return base.Channel.CreateUser(UserName, PassWord, uPath, userUname, userPassword, fName, mName, lName);
        }
        
        public bool AssignUserToGroup(string UserName, string PassWord, string usr_user, string groupPath) {
            return base.Channel.AssignUserToGroup(UserName, PassWord, usr_user, groupPath);
        }
        
        public bool DropUserFromGroup(string UserName, string PassWord, string usr_user, string groupPath) {
            return base.Channel.DropUserFromGroup(UserName, PassWord, usr_user, groupPath);
        }
        
        public bool DeleteUser(string UserName, string PassWord, string userUname) {
            return base.Channel.DeleteUser(UserName, PassWord, userUname);
        }
        
        public void UnlockUser(string UserName, string PassWord, string usr_user) {
            base.Channel.UnlockUser(UserName, PassWord, usr_user);
        }
        
        public bool RemoveUserFromGroup(string UserName, string PassWord, string usr_user, string groupPath) {
            return base.Channel.RemoveUserFromGroup(UserName, PassWord, usr_user, groupPath);
        }
    }
}
